version: '{build}'
os: Visual Studio 2017
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: DKo2bdhGoBM6xWG80X22iMy8gbJkM12oocf1A8P8lYFdiP9/aOH5bPF7UQaOwTh3
branches:
  only:
    - master
build_script:
- ps: ./Build.ps1
test_script:
- ps: ./Coverage.ps1
artifacts:
  - path: '**\*.nupkg'
    name: NuGet Packages
deploy:
  provider: NuGet
  api_key:
    secure: QeC34B7ohkvqbwCOKmavQWhitZNYLX/EFdgK8CfL5jEujWw2L85qrzuME8CQRBEb
  on:
    appveyor_repo_tag: true